import json

with open('terms_data.json', encoding='utf-8') as f:
    terms = json.load(f)

tr_alphabet = 'abcçdefgğhıijklmnoöprsştuüvyz'
char_map = {c: i for i, c in enumerate(tr_alphabet)}

def tr_sort_key(term):
    s = term['title'].lower()
    key = []
    for ch in s:
        key.append(char_map.get(ch, 999))
    return key

def get_first_letter(title):
    t = title.strip()
    if not t:
        return 'A'
    first = t[0]
    if first in ['i', 'İ']:
        return 'İ'
    if first in ['ı', 'I']:
        return 'I'
    return first.upper()

terms.sort(key=tr_sort_key)

lines = []
lines.append("// Autogenerated from AFAD & ESOGÜ Afetler ve Acil Durumlar İçin Görsel Sözlük")
lines.append("class DisasterTerm {")
lines.append("  final String id;")
lines.append("  final String title;")
lines.append("  final String category;")
lines.append("  final String definition;")
lines.append("  final String imageAsset;")
lines.append("  final String firstLetter;")
lines.append("")
lines.append("  const DisasterTerm({")
lines.append("    required this.id,")
lines.append("    required this.title,")
lines.append("    required this.category,")
lines.append("    required this.definition,")
lines.append("    required this.imageAsset,")
lines.append("    required this.firstLetter,")
lines.append("  });")
lines.append("}")
lines.append("")
lines.append("class DisasterDictionaryData {")
lines.append("  static const List<DisasterTerm> terms = [")

for idx, t in enumerate(terms):
    fl = get_first_letter(t['title'])
    img_path = 'assets/images/disaster_dict/' + t['img']
    title_esc = t['title'].replace("'", "\\'")
    def_esc = t['definition'].replace("'", "\\'")
    cat_esc = t['category'].replace("'", "\\'")
    lines.append("    DisasterTerm(")
    lines.append(f"      id: 'term_{idx + 1}',")
    lines.append(f"      title: '{title_esc}',")
    lines.append(f"      category: '{cat_esc}',")
    lines.append(f"      definition: '{def_esc}',")
    lines.append(f"      imageAsset: '{img_path}',")
    lines.append(f"      firstLetter: '{fl}',")
    lines.append("    ),")

lines.append("  ];")
lines.append("")
lines.append("  static List<String> get availableLetters {")
lines.append("    final letters = terms.map((t) => t.firstLetter).toSet().toList();")
lines.append("    letters.sort();")
lines.append("    return letters;")
lines.append("  }")
lines.append("}")
lines.append("")

with open('lib/data/disaster_dictionary_data.dart', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f"Generated lib/data/disaster_dictionary_data.dart with {len(terms)} terms.")
