import pymupdf
import re
import os
import json

doc = pymupdf.open('lezzet_kitabi.pdf')

recipe_defs = [
    {
        'id': 'ispanak_corbasi',
        'title': 'Ispanak Çorbası',
        'category': 'Çorbalar',
        'theme_color': '0xFF16A34A',
        'icon': 'Icons.soup_kitchen_rounded',
        'p_start': 24,
        'p_end': 29,
    },
    {
        'id': 'sebze_corbasi',
        'title': 'Sebze Çorbası',
        'category': 'Çorbalar',
        'theme_color': '0xFFEA580C',
        'icon': 'Icons.soup_kitchen_rounded',
        'p_start': 30,
        'p_end': 37,
    },
    {
        'id': 'patates_corbasi',
        'title': 'Patates Çorbası',
        'category': 'Çorbalar',
        'theme_color': '0xFFCA8A04',
        'icon': 'Icons.soup_kitchen_rounded',
        'p_start': 38,
        'p_end': 43,
    },
    {
        'id': 'brokoli_corbasi',
        'title': 'Brokoli Çorbası',
        'category': 'Çorbalar',
        'theme_color': '0xFF059669',
        'icon': 'Icons.soup_kitchen_rounded',
        'p_start': 44,
        'p_end': 53,
    },
    {
        'id': 'tavuklu_sezar_salata',
        'title': 'Tavuklu Sezar Salata',
        'category': 'Salatalar',
        'theme_color': '0xFF2563EB',
        'icon': 'Icons.eco_rounded',
        'p_start': 56,
        'p_end': 61,
    },
    {
        'id': 'roka_salatasi',
        'title': 'Roka Salatası',
        'category': 'Salatalar',
        'theme_color': '0xFF15803D',
        'icon': 'Icons.eco_rounded',
        'p_start': 62,
        'p_end': 67,
    },
    {
        'id': 'beyaz_peynirli_makarna',
        'title': 'Beyaz Peynirli ve Kremalı Dirsek Makarna',
        'category': 'Makarnalar',
        'theme_color': '0xFFD97706',
        'icon': 'Icons.dinner_dining_rounded',
        'p_start': 72,
        'p_end': 79,
    },
    {
        'id': 'kuru_domatesli_makarna',
        'title': 'Kuru Domates ve Ispanaklı Kelebek Makarna',
        'category': 'Makarnalar',
        'theme_color': '0xFFDC2626',
        'icon': 'Icons.dinner_dining_rounded',
        'p_start': 80,
        'p_end': 87,
    },
    {
        'id': 'mantar_soslu_makarna',
        'title': 'Mantar Soslu Penne Makarna',
        'category': 'Makarnalar',
        'theme_color': '0xFF9333EA',
        'icon': 'Icons.dinner_dining_rounded',
        'p_start': 88,
        'p_end': 95,
    },
    {
        'id': 'caprese_sandvic',
        'title': 'Caprese Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFFE11D48',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 100,
        'p_end': 103,
    },
    {
        'id': 'club_sandvic',
        'title': 'Club Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFF0284C7',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 104,
        'p_end': 111,
    },
    {
        'id': 'hamburger',
        'title': 'Hamburger',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFFB45309',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 112,
        'p_end': 119,
    },
    {
        'id': 'keci_peynirli_sandvic',
        'title': 'Keçi Peynirli Izgara Sebzeli Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFF0D9488',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 120,
        'p_end': 127,
    },
    {
        'id': 'kumru_sandvic',
        'title': 'Kumru Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFFE11D48',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 128,
        'p_end': 135,
    },
    {
        'id': 'tavuk_fume_sandvic',
        'title': 'Tavuk Füme Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFF4F46E5',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 136,
        'p_end': 139,
    },
    {
        'id': 'ton_balikli_sandvic',
        'title': 'Ton Balıklı Sandviç',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFF0284C7',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 140,
        'p_end': 143,
    },
    {
        'id': 'hindi_fume_lavas',
        'title': 'Lavaş Ekmeğine Sarılı Hindi Füme Dürüm',
        'category': 'Sandviçler & Burgerler',
        'theme_color': '0xFF7C3AED',
        'icon': 'Icons.lunch_dining_rounded',
        'p_start': 144,
        'p_end': 147,
    },
    {
        'id': 'bol_peynirli_pogaca',
        'title': 'Bol Peynirli Poğaça',
        'category': 'Tatlılar & Hamur İşleri',
        'theme_color': '0xFFD97706',
        'icon': 'Icons.bakery_dining_rounded',
        'p_start': 152,
        'p_end': 159,
    },
    {
        'id': 'minik_kekler',
        'title': 'Minik Kekler (Muffin)',
        'category': 'Tatlılar & Hamur İşleri',
        'theme_color': '0xFFDB2777',
        'icon': 'Icons.cake_rounded',
        'p_start': 160,
        'p_end': 167,
    },
    {
        'id': 'cikolata_toplari',
        'title': 'Çikolata Topları',
        'category': 'Tatlılar & Hamur İşleri',
        'theme_color': '0xFF78350F',
        'icon': 'Icons.cookie_rounded',
        'p_start': 168,
        'p_end': 173,
    },
    {
        'id': 'gulen_yuz_kurabiye',
        'title': 'Gülen Yüz Kurabiye',
        'category': 'Tatlılar & Hamur İşleri',
        'theme_color': '0xFFEAB308',
        'icon': 'Icons.sentiment_very_satisfied_rounded',
        'p_start': 174,
        'p_end': 181,
    },
]

print(f"Loaded {len(recipe_defs)} recipe definitions.")
